### ISSUE TITLE
docker version upgrade make graylog cannot start 

### ISSUE THREAD

**Issue by natk9** [Websoft9/ansible-graylog#16]
cannot output container version
![image](https://user-images.githubusercontent.com/40535348/144785692-d90491f0-216c-40f9-a8ca-dfa968f798f9.png)

Test 1.29.0 and v2.1.1 versions of docker
find v2.1.1 cannot start up container
![image](https://user-images.githubusercontent.com/40535348/144785647-18e232d3-2079-4b92-b236-199b9a427632.png)

**Comment by qiaofeng1227** [comment]
test OK on docker-compose1.29.0， error on v2.1.1 versions of docker-compose

**Comment by qiaofeng1227** [comment]
It's only occur on upgrade version.

**Comment by qiaofeng1227** [comment]
docker-compose error, this error is ignore on docker-composev1.29
![image](https://user-images.githubusercontent.com/43192516/144794950-fd4192fa-f125-4538-b2d0-b1322e2ea813.png)

**Comment by qiaofeng1227** [comment]
test OK
